import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createApp} from '../server/index.mjs';
test('server authentication, permissions and persistence',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'order-hub-auth-')),dbPath=path.join(dir,'test.sqlite');let app=createApp({dbPath});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));let origin='http://127.0.0.1:'+app.server.address().port;let count=0;const ok=(v,m)=>{assert.ok(v,m);count++};
async function request(route,{method='GET',body,session,originOverride}={}){const headers={};if(session?.cookie)headers.Cookie=session.cookie;if(method!=='GET'){headers['Content-Type']='application/json';headers.Origin=originOverride??origin;if(session?.csrf)headers['X-CSRF-Token']=session.csrf}const r=await fetch(origin+route,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});let j;try{j=await r.json()}catch{j={}}return {status:r.status,j,cookie:r.headers.get('set-cookie')?.split(';')[0]}}
try{let r=await request('/api/auth/status');ok(r.j.needsSetup,'initial setup available');r=await request('/api/state');ok(r.status===401,'anonymous cannot read data');r=await request('/api/actions',{method:'POST',body:{action:'retry-stock'}});ok(r.status===401,'anonymous cannot mutate');r=await request('/api/auth/setup',{method:'POST',originOverride:'https://attacker.example',body:{username:'rootadmin',name:'Admin',password:'Strong-test-password-01'}});ok(r.status===403,'cross-origin setup rejected');
r=await request('/api/auth/setup',{method:'POST',body:{username:'rootadmin',name:'Admin',password:'Strong-test-password-01'}});ok(r.status===201&&r.j.user.role==='admin','setup creates admin');const admin={cookie:r.cookie,csrf:r.j.csrf},adminId=r.j.user.id;ok(r.cookie?.includes('oh_session='),'session cookie set');r=await request('/api/auth/setup',{method:'POST',body:{username:'otheradmin',name:'Other',password:'Strong-test-password-01'}});ok(r.status===409,'first-run setup closes');
const users=[['warehouse01','warehouse'],['finance01','finance']];for(const [username,role]of users){r=await request('/api/users',{method:'POST',session:admin,body:{username,name:role,password:'Strong-test-password-02',role}});ok(r.status===201,'admin creates '+role)}
const login=async username=>{let r=await request('/api/auth/login',{method:'POST',body:{username,password:'Strong-test-password-02'}});ok(r.status===200,'login '+username);return {cookie:r.cookie,csrf:r.j.csrf,id:r.j.user.id}};let wh=await login('warehouse01'),fi=await login('finance01');
r=await request('/api/state',{session:wh});const forbidden=new Set(['price','cost','discount','refund','payouts','expenses','sales','fee','net']);function clean(v){if(!v||typeof v!=='object')return true;return Object.entries(v).every(([k,x])=>!forbidden.has(k)&&clean(x))}ok(r.status===200&&clean(r.j.data),'warehouse payload contains no finance fields');let product=r.j.data.products[0],initialStock=product.stock;
r=await request('/api/state',{session:fi});ok(r.status===200&&r.j.data.payouts.length>0&&r.j.data.products[0].cost>0,'finance reads reports');r=await request('/api/actions',{method:'POST',session:fi,body:{action:'stock-receive',sku:product.sku,qty:2,role:'admin'}});ok(r.status===403,'finance cannot mutate by forged role');r=await request('/api/users',{session:wh});ok(r.status===403,'warehouse cannot list accounts');r=await request('/api/connections',{session:fi});ok(r.status===403,'finance cannot manage connectors');r=await request('/api/actions',{method:'POST',session:{cookie:wh.cookie,csrf:'wrong'},body:{action:'stock-receive',sku:product.sku,qty:2}});ok(r.status===403,'CSRF token checked');r=await request('/api/actions',{method:'POST',session:wh,originOverride:'https://attacker.example',body:{action:'stock-receive',sku:product.sku,qty:2}});ok(r.status===403,'cross-origin mutation rejected');r=await request('/api/actions',{method:'POST',session:wh,body:{action:'stock-receive',sku:product.sku,qty:2}});ok(r.status===200,'warehouse stock receipt permitted');r=await request('/api/state',{session:wh});ok(r.j.data.products[0].stock===initialStock+2,'shared inventory persisted');
r=await request('/api/users/'+adminId,{method:'PATCH',session:admin,body:{active:false}});ok(r.status===409,'cannot disable last admin');r=await request('/api/users/'+wh.id,{method:'PATCH',session:admin,body:{role:'finance'}});ok(r.status===200,'admin can change role');r=await request('/api/state',{session:wh});ok(r.status===401,'role change revokes session');r=await request('/api/users/'+fi.id,{method:'PATCH',session:admin,body:{active:false}});ok(r.status===200,'admin can disable');r=await request('/api/state',{session:fi});ok(r.status===401,'disabled user session revoked');
r=await request('/api/connections',{method:'POST',session:admin,body:{channel:'Shopee',storeName:'ร้านสาธิต',storeUrl:'https://shopee.co.th/example',appSecret:'must-not-store'}});ok(r.status===200&&r.j.live===false,'connection drafts cannot claim live');r=await request('/api/connections',{session:admin});ok(r.j.drafts[0].storeName==='ร้านสาธิต'&&!JSON.stringify(r.j).includes('must-not-store'),'connection draft stored without arbitrary secrets');
for(const route of ['/server/seed.json','/.local/order-hub.sqlite','/Order_Hub_Prototype.html','/../server/index.mjs']){r=await request(route);ok(r.status===404,'private file blocked '+route)}const script=await fetch(origin+'/app.js').then(r=>r.text());ok(!script.includes('price:490')&&!script.includes('ลูกค้าสาธิต 001'),'browser source has no seeded financial dataset');
const stored=app.db.prepare('SELECT password_hash FROM users WHERE id=?').get(adminId).password_hash;ok(!stored.includes('Strong-test-password')&&stored.includes(':'),'passwords salted and hashed');r=await request('/api/auth/logout',{method:'POST',session:admin,body:{}});ok(r.status===200,'logout succeeds');r=await request('/api/state',{session:admin});ok(r.status===401,'logout invalidates server session');
await new Promise(r=>app.server.close(r));app=createApp({dbPath});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+app.server.address().port;r=await request('/api/auth/status');ok(!r.j.needsSetup,'accounts survive restart');r=await request('/api/auth/login',{method:'POST',body:{username:'rootadmin',password:'Strong-test-password-01'}});const resumed={cookie:r.cookie,csrf:r.j.csrf};r=await request('/api/state',{session:resumed});ok(r.j.data.products[0].stock===initialStock+2,'stock survives restart');r=await request('/api/connections',{session:resumed});ok(r.j.drafts.length===1,'connection setup survives restart');
fs.writeFileSync(path.resolve('qa/auth-results.json'),JSON.stringify({passed:count,errors:[],scope:'local server auth, role projection, mutation guards, sessions, persistence'},null,2));console.log(JSON.stringify({passed:count,errors:[]}));
}finally{await new Promise(r=>app.server.close(r));fs.rmSync(dir,{recursive:true,force:true})}});
